"""
Popula a tabela usuario com registros de exemplo.

Uso:
    python -m app.db.seeds.seed_usuarios
"""
from sqlmodel import Session, select

from app.db.session import create_db_and_tables, engine
from app.models.usuario import Usuario
from app.models.secretaria import Secretaria
from app.models.categoria import Categoria
from app.models.item import Item

from app.core.security import hash_senha

# lista simples de dicts — cada um vira 1 linha na tabela
USUARIOS_SEED = [
    {"nome": "Gestor SEAD", "email": "gestorsead@gmail.com", "senha_hash": hash_senha("senha"), "papel": "gestor", "secretaria_id": 1},
    {"nome": "Gestor SEDUC", "email": "gestorseduc@gmail.com", "senha_hash": hash_senha("senha"), "papel": "gestor", "secretaria_id": 2},
    {"nome": "Gestor SESA", "email": "gestorsesa@gmail.com", "senha_hash": hash_senha("senha"), "papel": "gestor", "secretaria_id": 3},
    {"nome": "Gestor SEFAZ", "email": "gestorsefaz@gmail.com", "senha_hash": hash_senha("senha"), "papel": "gestor", "secretaria_id": 4},
    {"nome": "Gestor SESP", "email": "gestorsesp@gmail.com", "senha_hash": hash_senha("senha"), "papel": "gestor", "secretaria_id": 5},
    {"nome": "Gestor SEINFRA", "email": "gestorseinfra@gmail.com", "senha_hash": hash_senha("senha"), "papel": "gestor", "secretaria_id": 6},
    {"nome": "Gestor SEMA", "email": "gestorsema@gmail.com", "senha_hash": hash_senha("senha"), "papel": "gestor", "secretaria_id": 7},
    {"nome": "Gestor SEAG", "email": "gestorseag@gmail.com", "senha_hash": hash_senha("senha"), "papel": "gestor", "secretaria_id": 8},
    {"nome": "Gestor SEAS", "email": "gestorseas@gmail.com", "senha_hash": hash_senha("senha"), "papel": "gestor", "secretaria_id": 9},
    {"nome": "Gestor SECULT", "email": "gestorsecult@gmail.com", "senha_hash": hash_senha("senha"), "papel": "gestor", "secretaria_id": 10},
    {"nome": "Gestor SEEL", "email": "gestorseel@gmail.com", "senha_hash": hash_senha("senha"), "papel": "gestor", "secretaria_id": 11},
    {"nome": "Gestor SEDEC", "email": "gestorsedec@gmail.com", "senha_hash": hash_senha("senha"), "papel": "gestor", "secretaria_id": 12},
    {"nome": "Secretaria SEAD", "email": "secretariasead@gmail.com", "senha_hash": hash_senha("senha"), "papel": "secretaria", "secretaria_id": 1},
    {"nome": "Secretaria SEDUC", "email": "secretariaseduc@gmail.com", "senha_hash": hash_senha("senha"), "papel": "secretaria", "secretaria_id": 2},
    {"nome": "Secretaria SESA", "email": "secretariasesa@gmail.com", "senha_hash": hash_senha("senha"), "papel": "secretaria", "secretaria_id": 3},
    {"nome": "Secretaria SEFAZ", "email": "secretariasefaz@gmail.com", "senha_hash": hash_senha("senha"), "papel": "secretaria", "secretaria_id": 4},
    {"nome": "Secretaria SESP", "email": "secretariasesp@gmail.com", "senha_hash": hash_senha("senha"), "papel": "secretaria", "secretaria_id": 5},
    {"nome": "Secretaria SEINFRA", "email": "secretariaseinfra@gmail.com", "senha_hash": hash_senha("senha"), "papel": "secretaria", "secretaria_id": 6},
    {"nome": "Secretaria SEMA", "email": "secretariasema@gmail.com", "senha_hash": hash_senha("senha"), "papel": "secretaria", "secretaria_id": 7},
    {"nome": "Secretaria SEAG", "email": "secretariaseag@gmail.com", "senha_hash": hash_senha("senha"), "papel": "secretaria", "secretaria_id": 8},
    {"nome": "Secretaria SEAS", "email": "secretariaseas@gmail.com", "senha_hash": hash_senha("senha"), "papel": "secretaria", "secretaria_id": 9},
    {"nome": "Secretaria SECULT", "email": "secretariasecult@gmail.com", "senha_hash": hash_senha("senha"), "papel": "secretaria", "secretaria_id": 10},
    {"nome": "Secretaria SEEL", "email": "secretariaseel@gmail.com", "senha_hash": hash_senha("senha"), "papel": "secretaria", "secretaria_id": 11},
    {"nome": "Secretaria SEDEC", "email": "secretariasedec@gmail.com", "senha_hash": hash_senha("senha"), "papel": "secretaria", "secretaria_id": 12},
]

SECRETARIAS_SEED = [
    {"nome": "Secretaria de Administração", "sigla": "SEAD"},
    {"nome": "Secretaria de Educação", "sigla": "SEDUC"},
    {"nome": "Secretaria de Saúde", "sigla": "SESA"},
    {"nome": "Secretaria da Fazenda", "sigla": "SEFAZ"},
    {"nome": "Secretaria de Segurança Pública", "sigla": "SESP"},
    {"nome": "Secretaria de Infraestrutura", "sigla": "SEINFRA"},
    {"nome": "Secretaria de Meio Ambiente", "sigla": "SEMA"},
    {"nome": "Secretaria de Agricultura", "sigla": "SEAG"},
    {"nome": "Secretaria de Assistência Social", "sigla": "SEAS"},
    {"nome": "Secretaria de Cultura", "sigla": "SECULT"},
    {"nome": "Secretaria de Esporte e Lazer", "sigla": "SEEL"},
    {"nome": "Secretaria de Desenvolvimento Econômico", "sigla": "SEDEC"},
]

CATEGORIAS_SEED = [
    {"nome": "Mobiliário"},
    {"nome": "Material de Escritório"},
    {"nome": "Informática e Eletrônicos"},
    {"nome": "Material de Limpeza e Higiene"},
    {"nome": "Ferramentas e Equipamentos"},
    {"nome": "Material Hospitalar e Odontológico"},
    {"nome": "Uniformes e Equipamentos de Segurança"},
    {"nome": "Material Esportivo e Cultural"},
]

ITENS_SEED = [
    {
        "nome": "Computador desktop",
        "descricao": "Computador completo para setor administrativo",
        "patrimonio": "PMF-2024-00001",
        "categoria_id": "3",
        "secretaria_id": "1",
        "quantidade": "30",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "2200.00",
        "catmat_code": "0000001",
    },
    {
        "nome": "Monitor LED 21 polegadas",
        "descricao": "Monitor LED Full HD 21 polegadas",
        "patrimonio": "PMF-2024-00002",
        "categoria_id": "3",
        "secretaria_id": "1",
        "quantidade": "25",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "650.00",
        "catmat_code": "0000002",
    },
    {
        "nome": "Impressora multifuncional laser",
        "descricao": "Impressora laser multifuncional em rede",
        "patrimonio": "PMF-2024-00003",
        "categoria_id": "3",
        "secretaria_id": "1",
        "quantidade": "10",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "1250.00",
        "catmat_code": "0000003",
    },
    {
        "nome": "Nobreak 1200VA",
        "descricao": "Nobreak para proteção de equipamentos",
        "patrimonio": "PMF-2024-00004",
        "categoria_id": "3",
        "secretaria_id": "1",
        "quantidade": "20",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "480.00",
        "catmat_code": "0000004",
    },
    {
        "nome": "Roteador wifi",
        "descricao": "Roteador wireless dual band",
        "patrimonio": "PMF-2024-00005",
        "categoria_id": "3",
        "secretaria_id": "1",
        "quantidade": "15",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "220.00",
        "catmat_code": "0000005",
    },
    {
        "nome": "Mesa de escritório em L",
        "descricao": "Mesa de escritório em MDF formato L",
        "patrimonio": "PMF-2024-00006",
        "categoria_id": "1",
        "secretaria_id": "1",
        "quantidade": "30",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "480.00",
        "catmat_code": "0000006",
    },
    {
        "nome": "Cadeira giratória ergonômica",
        "descricao": "Cadeira giratória com apoio lombar",
        "patrimonio": "PMF-2024-00007",
        "categoria_id": "1",
        "secretaria_id": "1",
        "quantidade": "40",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "350.00",
        "catmat_code": "0000007",
    },
    {
        "nome": "Armário de aço 2 portas",
        "descricao": "Armário de aço para escritório",
        "patrimonio": "PMF-2024-00008",
        "categoria_id": "1",
        "secretaria_id": "1",
        "quantidade": "20",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "620.00",
        "catmat_code": "0000008",
    },
    {
        "nome": "Arquivo morto de aço",
        "descricao": "Arquivo de aço para documentos antigos",
        "patrimonio": "PMF-2024-00009",
        "categoria_id": "1",
        "secretaria_id": "1",
        "quantidade": "15",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "580.00",
        "catmat_code": "0000009",
    },
    {
        "nome": "Ar condicionado split 12000 BTUs",
        "descricao": "Ar condicionado split para sala administrativa",
        "patrimonio": "PMF-2024-00010",
        "categoria_id": "3",
        "secretaria_id": "1",
        "quantidade": "12",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "2100.00",
        "catmat_code": "0000010",
    },
    {
        "nome": "Telefone fixo digital",
        "descricao": "Aparelho de telefone fixo digital",
        "patrimonio": "PMF-2024-00011",
        "categoria_id": "3",
        "secretaria_id": "1",
        "quantidade": "25",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "95.00",
        "catmat_code": "0000011",
    },
    {
        "nome": "Papel A4 (resma)",
        "descricao": "Resma de papel sulfite branco A4",
        "patrimonio": "PMF-2024-00012",
        "categoria_id": "2",
        "secretaria_id": "1",
        "quantidade": "200",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "24.90",
        "catmat_code": "0000012",
    },
    {
        "nome": "Grampeador de mesa",
        "descricao": "Grampeador metálico de mesa",
        "patrimonio": "PMF-2024-00013",
        "categoria_id": "2",
        "secretaria_id": "1",
        "quantidade": "40",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "22.00",
        "catmat_code": "0000013",
    },
    {
        "nome": "Perfurador de papel",
        "descricao": "Perfurador de duas furos",
        "patrimonio": "PMF-2024-00014",
        "categoria_id": "2",
        "secretaria_id": "1",
        "quantidade": "40",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "28.00",
        "catmat_code": "0000014",
    },
    {
        "nome": "Quadro de avisos",
        "descricao": "Quadro de avisos em cortiça",
        "patrimonio": "PMF-2024-00015",
        "categoria_id": "1",
        "secretaria_id": "1",
        "quantidade": "15",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "180.00",
        "catmat_code": "0000015",
    },
    {
        "nome": "Cofre de aço pequeno",
        "descricao": "Cofre de aço com senha digital",
        "patrimonio": "PMF-2024-00016",
        "categoria_id": "1",
        "secretaria_id": "1",
        "quantidade": "4",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "1200.00",
        "catmat_code": "0000016",
    },
    {
        "nome": "Extintor de incêndio",
        "descricao": "Extintor pó químico ABC 6kg",
        "patrimonio": "PMF-2024-00017",
        "categoria_id": "5",
        "secretaria_id": "1",
        "quantidade": "10",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "180.00",
        "catmat_code": "0000017",
    },
    {
        "nome": "Bebedouro elétrico",
        "descricao": "Bebedouro industrial de coluna",
        "patrimonio": "PMF-2024-00018",
        "categoria_id": "1",
        "secretaria_id": "1",
        "quantidade": "8",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "650.00",
        "catmat_code": "0000018",
    },
    {
        "nome": "Caneta esferográfica (caixa c/50)",
        "descricao": "Caneta azul esferográfica",
        "patrimonio": "PMF-2024-00019",
        "categoria_id": "2",
        "secretaria_id": "1",
        "quantidade": "60",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "18.00",
        "catmat_code": "0000019",
    },
    {
        "nome": "Pasta suspensa (caixa c/50)",
        "descricao": "Pasta suspensa kraft para arquivo",
        "patrimonio": "PMF-2024-00020",
        "categoria_id": "2",
        "secretaria_id": "1",
        "quantidade": "50",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "32.00",
        "catmat_code": "0000020",
    },
    {
        "nome": "Carteira escolar universitária",
        "descricao": "Carteira com tampo e assento em madeira",
        "patrimonio": "PMF-2024-00021",
        "categoria_id": "1",
        "secretaria_id": "2",
        "quantidade": "200",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "180.00",
        "catmat_code": "0000021",
    },
    {
        "nome": "Cadeira escolar plástica",
        "descricao": "Cadeira empilhável para sala de aula",
        "patrimonio": "PMF-2024-00022",
        "categoria_id": "1",
        "secretaria_id": "2",
        "quantidade": "250",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "95.00",
        "catmat_code": "0000022",
    },
    {
        "nome": "Quadro branco magnético",
        "descricao": "Quadro branco 2x1m com moldura de alumínio",
        "patrimonio": "PMF-2024-00023",
        "categoria_id": "1",
        "secretaria_id": "2",
        "quantidade": "30",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "320.00",
        "catmat_code": "0000023",
    },
    {
        "nome": "Mesa para professor",
        "descricao": "Mesa de madeira com gaveta",
        "patrimonio": "PMF-2024-00024",
        "categoria_id": "1",
        "secretaria_id": "2",
        "quantidade": "40",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "250.00",
        "catmat_code": "0000024",
    },
    {
        "nome": "Armário de aço para material didático",
        "descricao": "Armário 2 portas com prateleiras",
        "patrimonio": "PMF-2024-00025",
        "categoria_id": "1",
        "secretaria_id": "2",
        "quantidade": "25",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "480.00",
        "catmat_code": "0000025",
    },
    {
        "nome": "Computador desktop para laboratório",
        "descricao": "Computador completo para laboratório de informática",
        "patrimonio": "PMF-2024-00026",
        "categoria_id": "3",
        "secretaria_id": "2",
        "quantidade": "40",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "2100.00",
        "catmat_code": "0000026",
    },
    {
        "nome": "Projetor multimídia",
        "descricao": "Projetor multimídia 3500 lumens",
        "patrimonio": "PMF-2024-00027",
        "categoria_id": "3",
        "secretaria_id": "2",
        "quantidade": "15",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "1850.00",
        "catmat_code": "0000027",
    },
    {
        "nome": "Notebook para professores",
        "descricao": "Notebook 8GB RAM para uso pedagógico",
        "patrimonio": "PMF-2024-00028",
        "categoria_id": "3",
        "secretaria_id": "2",
        "quantidade": "20",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "3200.00",
        "catmat_code": "0000028",
    },
    {
        "nome": "Papel sulfite A4 (resma)",
        "descricao": "Resma de papel sulfite branco A4",
        "patrimonio": "PMF-2024-00029",
        "categoria_id": "2",
        "secretaria_id": "2",
        "quantidade": "150",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "24.90",
        "catmat_code": "0000029",
    },
    {
        "nome": "Caixa de giz escolar",
        "descricao": "Giz branco para quadro negro",
        "patrimonio": "PMF-2024-00030",
        "categoria_id": "2",
        "secretaria_id": "2",
        "quantidade": "100",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "8.50",
        "catmat_code": "0000030",
    },
    {
        "nome": "Caneta esferográfica (caixa c/50)",
        "descricao": "Caneta azul esferográfica",
        "patrimonio": "PMF-2024-00031",
        "categoria_id": "2",
        "secretaria_id": "2",
        "quantidade": "120",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "18.00",
        "catmat_code": "0000031",
    },
    {
        "nome": "Lápis grafite (caixa c/72)",
        "descricao": "Lápis grafite nº2",
        "patrimonio": "PMF-2024-00032",
        "categoria_id": "2",
        "secretaria_id": "2",
        "quantidade": "100",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "15.00",
        "catmat_code": "0000032",
    },
    {
        "nome": "Borracha escolar (caixa c/40)",
        "descricao": "Borracha branca macia",
        "patrimonio": "PMF-2024-00033",
        "categoria_id": "2",
        "secretaria_id": "2",
        "quantidade": "80",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "12.00",
        "catmat_code": "0000033",
    },
    {
        "nome": "Colchonete para educação física",
        "descricao": "Colchonete em espuma revestido",
        "patrimonio": "PMF-2024-00034",
        "categoria_id": "1",
        "secretaria_id": "2",
        "quantidade": "60",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "65.00",
        "catmat_code": "0000034",
    },
    {
        "nome": "Bola de futebol",
        "descricao": "Bola oficial para prática esportiva escolar",
        "patrimonio": "PMF-2024-00035",
        "categoria_id": "8",
        "secretaria_id": "2",
        "quantidade": "40",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "85.00",
        "catmat_code": "0000035",
    },
    {
        "nome": "Bebedouro elétrico",
        "descricao": "Bebedouro industrial de coluna",
        "patrimonio": "PMF-2024-00036",
        "categoria_id": "1",
        "secretaria_id": "2",
        "quantidade": "15",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "650.00",
        "catmat_code": "0000036",
    },
    {
        "nome": "Ventilador de parede",
        "descricao": "Ventilador de parede 60cm",
        "patrimonio": "PMF-2024-00037",
        "categoria_id": "1",
        "secretaria_id": "2",
        "quantidade": "60",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "145.00",
        "catmat_code": "0000037",
    },
    {
        "nome": "Extintor de incêndio",
        "descricao": "Extintor pó químico ABC 6kg",
        "patrimonio": "PMF-2024-00038",
        "categoria_id": "5",
        "secretaria_id": "2",
        "quantidade": "25",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "180.00",
        "catmat_code": "0000038",
    },
    {
        "nome": "Impressora multifuncional",
        "descricao": "Impressora laser multifuncional",
        "patrimonio": "PMF-2024-00039",
        "categoria_id": "3",
        "secretaria_id": "2",
        "quantidade": "10",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "890.00",
        "catmat_code": "0000039",
    },
    {
        "nome": "Livro didático (unidade)",
        "descricao": "Livro didático do ensino fundamental",
        "patrimonio": "PMF-2024-00040",
        "categoria_id": "2",
        "secretaria_id": "2",
        "quantidade": "500",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "45.00",
        "catmat_code": "0000040",
    },
    {
        "nome": "Maca hospitalar",
        "descricao": "Maca hospitalar com rodízios e grades laterais",
        "patrimonio": "PMF-2024-00041",
        "categoria_id": "1",
        "secretaria_id": "3",
        "quantidade": "5",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "850.00",
        "catmat_code": "0000041",
    },
    {
        "nome": "Cadeira de rodas",
        "descricao": "Cadeira de rodas dobrável em alumínio",
        "patrimonio": "PMF-2024-00042",
        "categoria_id": "1",
        "secretaria_id": "3",
        "quantidade": "8",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "620.00",
        "catmat_code": "0000042",
    },
    {
        "nome": "Armário de aço para medicamentos",
        "descricao": "Armário de aço com chave para farmácia básica",
        "patrimonio": "PMF-2024-00043",
        "categoria_id": "1",
        "secretaria_id": "3",
        "quantidade": "6",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "780.00",
        "catmat_code": "0000043",
    },
    {
        "nome": "Mesa de atendimento clínico",
        "descricao": "Mesa para consultório médico",
        "patrimonio": "PMF-2024-00044",
        "categoria_id": "1",
        "secretaria_id": "3",
        "quantidade": "10",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "430.00",
        "catmat_code": "0000044",
    },
    {
        "nome": "Cadeira estofada para consultório",
        "descricao": "Cadeira estofada com braços",
        "patrimonio": "PMF-2024-00045",
        "categoria_id": "1",
        "secretaria_id": "3",
        "quantidade": "15",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "310.00",
        "catmat_code": "0000045",
    },
    {
        "nome": "Computador desktop",
        "descricao": "Computador completo para posto de saúde",
        "patrimonio": "PMF-2024-00046",
        "categoria_id": "3",
        "secretaria_id": "3",
        "quantidade": "12",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "2200.00",
        "catmat_code": "0000046",
    },
    {
        "nome": "Impressora multifuncional",
        "descricao": "Impressora laser multifuncional",
        "patrimonio": "PMF-2024-00047",
        "categoria_id": "3",
        "secretaria_id": "3",
        "quantidade": "4",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "890.00",
        "catmat_code": "0000047",
    },
    {
        "nome": "Esfigmomanômetro digital",
        "descricao": "Aparelho de pressão digital de braço",
        "patrimonio": "PMF-2024-00048",
        "categoria_id": "6",
        "secretaria_id": "3",
        "quantidade": "20",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "180.00",
        "catmat_code": "0000048",
    },
    {
        "nome": "Oxímetro de pulso",
        "descricao": "Oxímetro de dedo digital",
        "patrimonio": "PMF-2024-00049",
        "categoria_id": "6",
        "secretaria_id": "3",
        "quantidade": "25",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "95.00",
        "catmat_code": "0000049",
    },
    {
        "nome": "Termômetro infravermelho",
        "descricao": "Termômetro digital sem contato",
        "patrimonio": "PMF-2024-00050",
        "categoria_id": "6",
        "secretaria_id": "3",
        "quantidade": "30",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "120.00",
        "catmat_code": "0000050",
    },
    {
        "nome": "Geladeira para vacinas",
        "descricao": "Geladeira própria para conservação de imunobiológicos",
        "patrimonio": "PMF-2024-00051",
        "categoria_id": "6",
        "secretaria_id": "3",
        "quantidade": "3",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "3200.00",
        "catmat_code": "0000051",
    },
    {
        "nome": "Kit de curativo completo",
        "descricao": "Kit descartável para curativos",
        "patrimonio": "PMF-2024-00052",
        "categoria_id": "6",
        "secretaria_id": "3",
        "quantidade": "50",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "35.00",
        "catmat_code": "0000052",
    },
    {
        "nome": "Luva de procedimento (caixa c/100)",
        "descricao": "Luva de látex descartável",
        "patrimonio": "PMF-2024-00053",
        "categoria_id": "6",
        "secretaria_id": "3",
        "quantidade": "200",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "28.50",
        "catmat_code": "0000053",
    },
    {
        "nome": "Máscara cirúrgica descartável (caixa c/50)",
        "descricao": "Máscara tripla camada",
        "patrimonio": "PMF-2024-00054",
        "categoria_id": "6",
        "secretaria_id": "3",
        "quantidade": "150",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "22.00",
        "catmat_code": "0000054",
    },
    {
        "nome": "Álcool 70% (litro)",
        "descricao": "Álcool etílico para antissepsia",
        "patrimonio": "PMF-2024-00055",
        "categoria_id": "4",
        "secretaria_id": "3",
        "quantidade": "100",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "12.50",
        "catmat_code": "0000055",
    },
    {
        "nome": "Sabonete líquido antisséptico (litro)",
        "descricao": "Sabonete para higienização das mãos",
        "patrimonio": "PMF-2024-00056",
        "categoria_id": "4",
        "secretaria_id": "3",
        "quantidade": "80",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "15.00",
        "catmat_code": "0000056",
    },
    {
        "nome": "Ventilador de teto",
        "descricao": "Ventilador de teto 3 pás",
        "patrimonio": "PMF-2024-00057",
        "categoria_id": "1",
        "secretaria_id": "3",
        "quantidade": "20",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "145.00",
        "catmat_code": "0000057",
    },
    {
        "nome": "Bebedouro elétrico",
        "descricao": "Bebedouro industrial de coluna",
        "patrimonio": "PMF-2024-00058",
        "categoria_id": "1",
        "secretaria_id": "3",
        "quantidade": "8",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "650.00",
        "catmat_code": "0000058",
    },
    {
        "nome": "Extintor de incêndio",
        "descricao": "Extintor pó químico ABC 6kg",
        "patrimonio": "PMF-2024-00059",
        "categoria_id": "5",
        "secretaria_id": "3",
        "quantidade": "15",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "180.00",
        "catmat_code": "0000059",
    },
    {
        "nome": "Papel A4 (resma)",
        "descricao": "Resma de papel sulfite branco A4",
        "patrimonio": "PMF-2024-00060",
        "categoria_id": "2",
        "secretaria_id": "3",
        "quantidade": "60",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "24.90",
        "catmat_code": "0000060",
    },
    {
        "nome": "Computador desktop",
        "descricao": "Computador completo para setor de arrecadação",
        "patrimonio": "PMF-2024-00061",
        "categoria_id": "3",
        "secretaria_id": "4",
        "quantidade": "20",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "2200.00",
        "catmat_code": "0000061",
    },
    {
        "nome": "Monitor LED 21 polegadas",
        "descricao": "Monitor LED Full HD 21 polegadas",
        "patrimonio": "PMF-2024-00062",
        "categoria_id": "3",
        "secretaria_id": "4",
        "quantidade": "15",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "650.00",
        "catmat_code": "0000062",
    },
    {
        "nome": "Impressora fiscal térmica",
        "descricao": "Impressora térmica para documentos fiscais",
        "patrimonio": "PMF-2024-00063",
        "categoria_id": "3",
        "secretaria_id": "4",
        "quantidade": "8",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "1450.00",
        "catmat_code": "0000063",
    },
    {
        "nome": "Nobreak 1200VA",
        "descricao": "Nobreak para proteção de equipamentos",
        "patrimonio": "PMF-2024-00064",
        "categoria_id": "3",
        "secretaria_id": "4",
        "quantidade": "15",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "480.00",
        "catmat_code": "0000064",
    },
    {
        "nome": "Cofre de aço grande",
        "descricao": "Cofre de aço reforçado com fechadura digital",
        "patrimonio": "PMF-2024-00065",
        "categoria_id": "1",
        "secretaria_id": "4",
        "quantidade": "3",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "3200.00",
        "catmat_code": "0000065",
    },
    {
        "nome": "Mesa de escritório em L",
        "descricao": "Mesa de escritório em MDF formato L",
        "patrimonio": "PMF-2024-00066",
        "categoria_id": "1",
        "secretaria_id": "4",
        "quantidade": "20",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "480.00",
        "catmat_code": "0000066",
    },
    {
        "nome": "Cadeira giratória ergonômica",
        "descricao": "Cadeira giratória com apoio lombar",
        "patrimonio": "PMF-2024-00067",
        "categoria_id": "1",
        "secretaria_id": "4",
        "quantidade": "25",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "350.00",
        "catmat_code": "0000067",
    },
    {
        "nome": "Armário de aço 2 portas",
        "descricao": "Armário de aço para escritório",
        "patrimonio": "PMF-2024-00068",
        "categoria_id": "1",
        "secretaria_id": "4",
        "quantidade": "15",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "620.00",
        "catmat_code": "0000068",
    },
    {
        "nome": "Arquivo de aço 4 gavetas",
        "descricao": "Arquivo de aço para documentos fiscais",
        "patrimonio": "PMF-2024-00069",
        "categoria_id": "1",
        "secretaria_id": "4",
        "quantidade": "12",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "620.00",
        "catmat_code": "0000069",
    },
    {
        "nome": "Calculadora de mesa",
        "descricao": "Calculadora de mesa 12 dígitos",
        "patrimonio": "PMF-2024-00070",
        "categoria_id": "2",
        "secretaria_id": "4",
        "quantidade": "30",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "45.00",
        "catmat_code": "0000070",
    },
    {
        "nome": "Papel A4 (resma)",
        "descricao": "Resma de papel sulfite branco A4",
        "patrimonio": "PMF-2024-00071",
        "categoria_id": "2",
        "secretaria_id": "4",
        "quantidade": "150",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "24.90",
        "catmat_code": "0000071",
    },
    {
        "nome": "Grampeador de mesa",
        "descricao": "Grampeador metálico de mesa",
        "patrimonio": "PMF-2024-00072",
        "categoria_id": "2",
        "secretaria_id": "4",
        "quantidade": "30",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "22.00",
        "catmat_code": "0000072",
    },
    {
        "nome": "Pasta suspensa (caixa c/50)",
        "descricao": "Pasta suspensa kraft para arquivo",
        "patrimonio": "PMF-2024-00073",
        "categoria_id": "2",
        "secretaria_id": "4",
        "quantidade": "40",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "32.00",
        "catmat_code": "0000073",
    },
    {
        "nome": "Carimbo automático",
        "descricao": "Carimbo automático personalizado",
        "patrimonio": "PMF-2024-00074",
        "categoria_id": "2",
        "secretaria_id": "4",
        "quantidade": "25",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "38.00",
        "catmat_code": "0000074",
    },
    {
        "nome": "Extintor de incêndio",
        "descricao": "Extintor pó químico ABC 6kg",
        "patrimonio": "PMF-2024-00075",
        "categoria_id": "5",
        "secretaria_id": "4",
        "quantidade": "10",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "180.00",
        "catmat_code": "0000075",
    },
    {
        "nome": "Bebedouro elétrico",
        "descricao": "Bebedouro industrial de coluna",
        "patrimonio": "PMF-2024-00076",
        "categoria_id": "1",
        "secretaria_id": "4",
        "quantidade": "8",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "650.00",
        "catmat_code": "0000076",
    },
    {
        "nome": "Ar condicionado split 12000 BTUs",
        "descricao": "Ar condicionado split para sala administrativa",
        "patrimonio": "PMF-2024-00077",
        "categoria_id": "3",
        "secretaria_id": "4",
        "quantidade": "10",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "2100.00",
        "catmat_code": "0000077",
    },
    {
        "nome": "Telefone fixo digital",
        "descricao": "Aparelho de telefone fixo digital",
        "patrimonio": "PMF-2024-00078",
        "categoria_id": "3",
        "secretaria_id": "4",
        "quantidade": "20",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "95.00",
        "catmat_code": "0000078",
    },
    {
        "nome": "Scanner de mesa",
        "descricao": "Scanner de documentos de mesa",
        "patrimonio": "PMF-2024-00079",
        "categoria_id": "3",
        "secretaria_id": "4",
        "quantidade": "6",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "780.00",
        "catmat_code": "0000079",
    },
    {
        "nome": "Quadro de avisos",
        "descricao": "Quadro de avisos em cortiça",
        "patrimonio": "PMF-2024-00080",
        "categoria_id": "1",
        "secretaria_id": "4",
        "quantidade": "10",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "180.00",
        "catmat_code": "0000080",
    },
    {
        "nome": "Rádio comunicador HT",
        "descricao": "Rádio portátil para comunicação de equipes",
        "patrimonio": "PMF-2024-00081",
        "categoria_id": "3",
        "secretaria_id": "5",
        "quantidade": "40",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "650.00",
        "catmat_code": "0000081",
    },
    {
        "nome": "Lanterna tática recarregável",
        "descricao": "Lanterna tática de alta potência",
        "patrimonio": "PMF-2024-00082",
        "categoria_id": "5",
        "secretaria_id": "5",
        "quantidade": "50",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "120.00",
        "catmat_code": "0000082",
    },
    {
        "nome": "Colete de identificação refletivo",
        "descricao": "Colete refletivo para identificação de agente",
        "patrimonio": "PMF-2024-00083",
        "categoria_id": "7",
        "secretaria_id": "5",
        "quantidade": "60",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "45.00",
        "catmat_code": "0000083",
    },
    {
        "nome": "Capacete de proteção",
        "descricao": "Capacete de proteção para atividades de risco",
        "patrimonio": "PMF-2024-00084",
        "categoria_id": "7",
        "secretaria_id": "5",
        "quantidade": "40",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "180.00",
        "catmat_code": "0000084",
    },
    {
        "nome": "Uniforme completo (conjunto)",
        "descricao": "Conjunto de farda padrão",
        "patrimonio": "PMF-2024-00085",
        "categoria_id": "7",
        "secretaria_id": "5",
        "quantidade": "80",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "320.00",
        "catmat_code": "0000085",
    },
    {
        "nome": "Botina tática",
        "descricao": "Botina de proteção para uso operacional",
        "patrimonio": "PMF-2024-00086",
        "categoria_id": "7",
        "secretaria_id": "5",
        "quantidade": "60",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "220.00",
        "catmat_code": "0000086",
    },
    {
        "nome": "Capa de chuva",
        "descricao": "Capa de chuva impermeável",
        "patrimonio": "PMF-2024-00087",
        "categoria_id": "7",
        "secretaria_id": "5",
        "quantidade": "50",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "65.00",
        "catmat_code": "0000087",
    },
    {
        "nome": "Algema de contenção",
        "descricao": "Algema padrão para contenção",
        "patrimonio": "PMF-2024-00088",
        "categoria_id": "7",
        "secretaria_id": "5",
        "quantidade": "20",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "85.00",
        "catmat_code": "0000088",
    },
    {
        "nome": "Apito de sinalização",
        "descricao": "Apito para sinalização de trânsito e ronda",
        "patrimonio": "PMF-2024-00089",
        "categoria_id": "5",
        "secretaria_id": "5",
        "quantidade": "40",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "12.00",
        "catmat_code": "0000089",
    },
    {
        "nome": "Megafone portátil",
        "descricao": "Megafone portátil para orientação em eventos",
        "patrimonio": "PMF-2024-00090",
        "categoria_id": "3",
        "secretaria_id": "5",
        "quantidade": "15",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "380.00",
        "catmat_code": "0000090",
    },
    {
        "nome": "Cone de sinalização",
        "descricao": "Cone de sinalização de trânsito 75cm",
        "patrimonio": "PMF-2024-00091",
        "categoria_id": "5",
        "secretaria_id": "5",
        "quantidade": "100",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "25.00",
        "catmat_code": "0000091",
    },
    {
        "nome": "Fita zebrada de isolamento (rolo)",
        "descricao": "Fita para isolamento de área",
        "patrimonio": "PMF-2024-00092",
        "categoria_id": "5",
        "secretaria_id": "5",
        "quantidade": "80",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "18.00",
        "catmat_code": "0000092",
    },
    {
        "nome": "Câmera de monitoramento",
        "descricao": "Câmera de segurança para vigilância urbana",
        "patrimonio": "PMF-2024-00093",
        "categoria_id": "3",
        "secretaria_id": "5",
        "quantidade": "30",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "850.00",
        "catmat_code": "0000093",
    },
    {
        "nome": "Central de monitoramento (kit)",
        "descricao": "Kit de central de monitoramento por vídeo",
        "patrimonio": "PMF-2024-00094",
        "categoria_id": "3",
        "secretaria_id": "5",
        "quantidade": "3",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "4500.00",
        "catmat_code": "0000094",
    },
    {
        "nome": "Bicicleta para ronda",
        "descricao": "Bicicleta utilizada em patrulhamento",
        "patrimonio": "PMF-2024-00095",
        "categoria_id": "5",
        "secretaria_id": "5",
        "quantidade": "15",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "850.00",
        "catmat_code": "0000095",
    },
    {
        "nome": "Extintor de incêndio",
        "descricao": "Extintor pó químico ABC 6kg",
        "patrimonio": "PMF-2024-00096",
        "categoria_id": "5",
        "secretaria_id": "5",
        "quantidade": "20",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "180.00",
        "catmat_code": "0000096",
    },
    {
        "nome": "Gerador de energia portátil",
        "descricao": "Gerador a gasolina 5000W",
        "patrimonio": "PMF-2024-00097",
        "categoria_id": "5",
        "secretaria_id": "5",
        "quantidade": "5",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "2800.00",
        "catmat_code": "0000097",
    },
    {
        "nome": "Computador desktop",
        "descricao": "Computador completo para central de operações",
        "patrimonio": "PMF-2024-00098",
        "categoria_id": "3",
        "secretaria_id": "5",
        "quantidade": "15",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "2200.00",
        "catmat_code": "0000098",
    },
    {
        "nome": "Mesa de escritório",
        "descricao": "Mesa de escritório padrão",
        "patrimonio": "PMF-2024-00099",
        "categoria_id": "1",
        "secretaria_id": "5",
        "quantidade": "15",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "480.00",
        "catmat_code": "0000099",
    },
    {
        "nome": "Armário de aço para equipamentos",
        "descricao": "Armário de aço para guarda de equipamentos",
        "patrimonio": "PMF-2024-00100",
        "categoria_id": "1",
        "secretaria_id": "5",
        "quantidade": "10",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "680.00",
        "catmat_code": "0000100",
    },
    {
        "nome": "Pá de bico",
        "descricao": "Pá de bico com cabo de madeira",
        "patrimonio": "PMF-2024-00101",
        "categoria_id": "5",
        "secretaria_id": "6",
        "quantidade": "40",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "45.00",
        "catmat_code": "0000101",
    },
    {
        "nome": "Enxada",
        "descricao": "Enxada com cabo de madeira",
        "patrimonio": "PMF-2024-00102",
        "categoria_id": "5",
        "secretaria_id": "6",
        "quantidade": "40",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "38.00",
        "catmat_code": "0000102",
    },
    {
        "nome": "Carrinho de mão",
        "descricao": "Carrinho de mão em chapa de aço",
        "patrimonio": "PMF-2024-00103",
        "categoria_id": "5",
        "secretaria_id": "6",
        "quantidade": "25",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "220.00",
        "catmat_code": "0000103",
    },
    {
        "nome": "Capacete de segurança",
        "descricao": "Capacete de segurança tipo EPI",
        "patrimonio": "PMF-2024-00104",
        "categoria_id": "7",
        "secretaria_id": "6",
        "quantidade": "60",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "35.00",
        "catmat_code": "0000104",
    },
    {
        "nome": "Luva de raspa",
        "descricao": "Luva de raspa de couro para proteção",
        "patrimonio": "PMF-2024-00105",
        "categoria_id": "7",
        "secretaria_id": "6",
        "quantidade": "80",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "18.00",
        "catmat_code": "0000105",
    },
    {
        "nome": "Furadeira de impacto",
        "descricao": "Furadeira de impacto 1/2 polegada",
        "patrimonio": "PMF-2024-00106",
        "categoria_id": "5",
        "secretaria_id": "6",
        "quantidade": "15",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "380.00",
        "catmat_code": "0000106",
    },
    {
        "nome": "Betoneira 400 litros",
        "descricao": "Betoneira estacionária 400L",
        "patrimonio": "PMF-2024-00107",
        "categoria_id": "5",
        "secretaria_id": "6",
        "quantidade": "5",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "4200.00",
        "catmat_code": "0000107",
    },
    {
        "nome": "Martelo de unha",
        "descricao": "Martelo de unha com cabo de fibra",
        "patrimonio": "PMF-2024-00108",
        "categoria_id": "5",
        "secretaria_id": "6",
        "quantidade": "30",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "32.00",
        "catmat_code": "0000108",
    },
    {
        "nome": "Trena a laser",
        "descricao": "Trena digital a laser 50m",
        "patrimonio": "PMF-2024-00109",
        "categoria_id": "5",
        "secretaria_id": "6",
        "quantidade": "10",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "280.00",
        "catmat_code": "0000109",
    },
    {
        "nome": "Cone de sinalização",
        "descricao": "Cone de sinalização de trânsito 75cm",
        "patrimonio": "PMF-2024-00110",
        "categoria_id": "5",
        "secretaria_id": "6",
        "quantidade": "100",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "25.00",
        "catmat_code": "0000110",
    },
    {
        "nome": "Colete refletivo",
        "descricao": "Colete de segurança refletivo",
        "patrimonio": "PMF-2024-00111",
        "categoria_id": "7",
        "secretaria_id": "6",
        "quantidade": "70",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "22.00",
        "catmat_code": "0000111",
    },
    {
        "nome": "Cimento CP-II (saco 50kg)",
        "descricao": "Cimento para construção civil",
        "patrimonio": "PMF-2024-00112",
        "categoria_id": "5",
        "secretaria_id": "6",
        "quantidade": "300",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "32.00",
        "catmat_code": "0000112",
    },
    {
        "nome": "Tinta para sinalização viária (galão)",
        "descricao": "Tinta para pintura de vias e faixas",
        "patrimonio": "PMF-2024-00113",
        "categoria_id": "5",
        "secretaria_id": "6",
        "quantidade": "40",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "95.00",
        "catmat_code": "0000113",
    },
    {
        "nome": "Escada de alumínio",
        "descricao": "Escada extensível de alumínio 5m",
        "patrimonio": "PMF-2024-00114",
        "categoria_id": "5",
        "secretaria_id": "6",
        "quantidade": "12",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "350.00",
        "catmat_code": "0000114",
    },
    {
        "nome": "Motosserra",
        "descricao": "Motosserra a gasolina",
        "patrimonio": "PMF-2024-00115",
        "categoria_id": "5",
        "secretaria_id": "6",
        "quantidade": "8",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "1200.00",
        "catmat_code": "0000115",
    },
    {
        "nome": "Roçadeira lateral",
        "descricao": "Roçadeira costal a gasolina",
        "patrimonio": "PMF-2024-00116",
        "categoria_id": "5",
        "secretaria_id": "6",
        "quantidade": "10",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "950.00",
        "catmat_code": "0000116",
    },
    {
        "nome": "Gerador de energia portátil",
        "descricao": "Gerador a gasolina 5000W",
        "patrimonio": "PMF-2024-00117",
        "categoria_id": "5",
        "secretaria_id": "6",
        "quantidade": "4",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "2800.00",
        "catmat_code": "0000117",
    },
    {
        "nome": "Extensão elétrica 50m",
        "descricao": "Extensão elétrica com carretel",
        "patrimonio": "PMF-2024-00118",
        "categoria_id": "5",
        "secretaria_id": "6",
        "quantidade": "20",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "180.00",
        "catmat_code": "0000118",
    },
    {
        "nome": "Computador desktop (setor técnico)",
        "descricao": "Computador completo para setor de engenharia",
        "patrimonio": "PMF-2024-00119",
        "categoria_id": "3",
        "secretaria_id": "6",
        "quantidade": "8",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "2200.00",
        "catmat_code": "0000119",
    },
    {
        "nome": "Armário de ferramentas de aço",
        "descricao": "Armário de aço para ferramentaria",
        "patrimonio": "PMF-2024-00120",
        "categoria_id": "1",
        "secretaria_id": "6",
        "quantidade": "6",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "680.00",
        "catmat_code": "0000120",
    },
    {
        "nome": "Viveiro de mudas (kit estrutura)",
        "descricao": "Estrutura para viveiro de mudas nativas",
        "patrimonio": "PMF-2024-00121",
        "categoria_id": "5",
        "secretaria_id": "7",
        "quantidade": "5",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "1200.00",
        "catmat_code": "0000121",
    },
    {
        "nome": "Mudas de árvores nativas (unidade)",
        "descricao": "Mudas para reflorestamento urbano",
        "patrimonio": "PMF-2024-00122",
        "categoria_id": "5",
        "secretaria_id": "7",
        "quantidade": "500",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "8.50",
        "catmat_code": "0000122",
    },
    {
        "nome": "Kit de análise de água",
        "descricao": "Kit para análise de qualidade da água",
        "patrimonio": "PMF-2024-00123",
        "categoria_id": "5",
        "secretaria_id": "7",
        "quantidade": "8",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "950.00",
        "catmat_code": "0000123",
    },
    {
        "nome": "Luva de proteção",
        "descricao": "Luva de proteção para manejo ambiental",
        "patrimonio": "PMF-2024-00124",
        "categoria_id": "7",
        "secretaria_id": "7",
        "quantidade": "60",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "15.00",
        "catmat_code": "0000124",
    },
    {
        "nome": "Capacete de segurança",
        "descricao": "Capacete de segurança tipo EPI",
        "patrimonio": "PMF-2024-00125",
        "categoria_id": "7",
        "secretaria_id": "7",
        "quantidade": "30",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "35.00",
        "catmat_code": "0000125",
    },
    {
        "nome": "Botina de segurança",
        "descricao": "Botina de couro com bico de PVC",
        "patrimonio": "PMF-2024-00126",
        "categoria_id": "7",
        "secretaria_id": "7",
        "quantidade": "40",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "95.00",
        "catmat_code": "0000126",
    },
    {
        "nome": "Motosserra",
        "descricao": "Motosserra a gasolina",
        "patrimonio": "PMF-2024-00127",
        "categoria_id": "5",
        "secretaria_id": "7",
        "quantidade": "6",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "1200.00",
        "catmat_code": "0000127",
    },
    {
        "nome": "Roçadeira costal",
        "descricao": "Roçadeira costal a gasolina",
        "patrimonio": "PMF-2024-00128",
        "categoria_id": "5",
        "secretaria_id": "7",
        "quantidade": "12",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "950.00",
        "catmat_code": "0000128",
    },
    {
        "nome": "Contentor de coleta seletiva",
        "descricao": "Contentor plástico para resíduos recicláveis",
        "patrimonio": "PMF-2024-00129",
        "categoria_id": "1",
        "secretaria_id": "7",
        "quantidade": "30",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "320.00",
        "catmat_code": "0000129",
    },
    {
        "nome": "Regador de jardim",
        "descricao": "Regador plástico 10 litros",
        "patrimonio": "PMF-2024-00130",
        "categoria_id": "5",
        "secretaria_id": "7",
        "quantidade": "20",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "22.00",
        "catmat_code": "0000130",
    },
    {
        "nome": "Mangueira de jardim 50m",
        "descricao": "Mangueira flexível para irrigação",
        "patrimonio": "PMF-2024-00131",
        "categoria_id": "5",
        "secretaria_id": "7",
        "quantidade": "12",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "120.00",
        "catmat_code": "0000131",
    },
    {
        "nome": "Pulverizador costal manual",
        "descricao": "Pulverizador costal 20 litros",
        "patrimonio": "PMF-2024-00132",
        "categoria_id": "5",
        "secretaria_id": "7",
        "quantidade": "10",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "180.00",
        "catmat_code": "0000132",
    },
    {
        "nome": "Computador desktop",
        "descricao": "Computador completo para setor ambiental",
        "patrimonio": "PMF-2024-00133",
        "categoria_id": "3",
        "secretaria_id": "7",
        "quantidade": "8",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "2200.00",
        "catmat_code": "0000133",
    },
    {
        "nome": "Impressora multifuncional",
        "descricao": "Impressora laser multifuncional",
        "patrimonio": "PMF-2024-00134",
        "categoria_id": "3",
        "secretaria_id": "7",
        "quantidade": "4",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "890.00",
        "catmat_code": "0000134",
    },
    {
        "nome": "Mesa de escritório",
        "descricao": "Mesa de escritório padrão",
        "patrimonio": "PMF-2024-00135",
        "categoria_id": "1",
        "secretaria_id": "7",
        "quantidade": "10",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "480.00",
        "catmat_code": "0000135",
    },
    {
        "nome": "Cadeira giratória",
        "descricao": "Cadeira giratória com apoio lombar",
        "patrimonio": "PMF-2024-00136",
        "categoria_id": "1",
        "secretaria_id": "7",
        "quantidade": "15",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "350.00",
        "catmat_code": "0000136",
    },
    {
        "nome": "Armário de aço",
        "descricao": "Armário de aço para escritório",
        "patrimonio": "PMF-2024-00137",
        "categoria_id": "1",
        "secretaria_id": "7",
        "quantidade": "8",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "620.00",
        "catmat_code": "0000137",
    },
    {
        "nome": "Extintor de incêndio",
        "descricao": "Extintor pó químico ABC 6kg",
        "patrimonio": "PMF-2024-00138",
        "categoria_id": "5",
        "secretaria_id": "7",
        "quantidade": "8",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "180.00",
        "catmat_code": "0000138",
    },
    {
        "nome": "Gerador de energia portátil",
        "descricao": "Gerador a gasolina 5000W",
        "patrimonio": "PMF-2024-00139",
        "categoria_id": "5",
        "secretaria_id": "7",
        "quantidade": "3",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "2800.00",
        "catmat_code": "0000139",
    },
    {
        "nome": "Papel A4 (resma)",
        "descricao": "Resma de papel sulfite branco A4",
        "patrimonio": "PMF-2024-00140",
        "categoria_id": "2",
        "secretaria_id": "7",
        "quantidade": "40",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "24.90",
        "catmat_code": "0000140",
    },
    {
        "nome": "Trator agrícola compacto",
        "descricao": "Trator compacto para apoio a pequenos produtores",
        "patrimonio": "PMF-2024-00141",
        "categoria_id": "5",
        "secretaria_id": "8",
        "quantidade": "2",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "45000.00",
        "catmat_code": "0000141",
    },
    {
        "nome": "Enxada",
        "descricao": "Enxada com cabo de madeira",
        "patrimonio": "PMF-2024-00142",
        "categoria_id": "5",
        "secretaria_id": "8",
        "quantidade": "30",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "38.00",
        "catmat_code": "0000142",
    },
    {
        "nome": "Pá de bico",
        "descricao": "Pá de bico com cabo de madeira",
        "patrimonio": "PMF-2024-00143",
        "categoria_id": "5",
        "secretaria_id": "8",
        "quantidade": "30",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "45.00",
        "catmat_code": "0000143",
    },
    {
        "nome": "Adubo orgânico (saco 25kg)",
        "descricao": "Adubo orgânico para plantio",
        "patrimonio": "PMF-2024-00144",
        "categoria_id": "5",
        "secretaria_id": "8",
        "quantidade": "100",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "28.00",
        "catmat_code": "0000144",
    },
    {
        "nome": "Sementes diversas (kit)",
        "descricao": "Kit de sementes para hortas comunitárias",
        "patrimonio": "PMF-2024-00145",
        "categoria_id": "5",
        "secretaria_id": "8",
        "quantidade": "80",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "18.00",
        "catmat_code": "0000145",
    },
    {
        "nome": "Kit de análise de solo",
        "descricao": "Kit para análise de pH e nutrientes do solo",
        "patrimonio": "PMF-2024-00146",
        "categoria_id": "5",
        "secretaria_id": "8",
        "quantidade": "5",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "850.00",
        "catmat_code": "0000146",
    },
    {
        "nome": "Carrinho de mão",
        "descricao": "Carrinho de mão em chapa de aço",
        "patrimonio": "PMF-2024-00147",
        "categoria_id": "5",
        "secretaria_id": "8",
        "quantidade": "15",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "220.00",
        "catmat_code": "0000147",
    },
    {
        "nome": "Tesoura de poda",
        "descricao": "Tesoura de poda manual",
        "patrimonio": "PMF-2024-00148",
        "categoria_id": "5",
        "secretaria_id": "8",
        "quantidade": "25",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "45.00",
        "catmat_code": "0000148",
    },
    {
        "nome": "Luva de jardinagem",
        "descricao": "Luva de proteção para jardinagem",
        "patrimonio": "PMF-2024-00149",
        "categoria_id": "7",
        "secretaria_id": "8",
        "quantidade": "50",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "15.00",
        "catmat_code": "0000149",
    },
    {
        "nome": "Capacete de segurança",
        "descricao": "Capacete de segurança tipo EPI",
        "patrimonio": "PMF-2024-00150",
        "categoria_id": "7",
        "secretaria_id": "8",
        "quantidade": "20",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "35.00",
        "catmat_code": "0000150",
    },
    {
        "nome": "Botina de segurança",
        "descricao": "Botina de couro com bico de PVC",
        "patrimonio": "PMF-2024-00151",
        "categoria_id": "7",
        "secretaria_id": "8",
        "quantidade": "30",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "95.00",
        "catmat_code": "0000151",
    },
    {
        "nome": "Pulverizador costal manual",
        "descricao": "Pulverizador costal 20 litros",
        "patrimonio": "PMF-2024-00152",
        "categoria_id": "5",
        "secretaria_id": "8",
        "quantidade": "12",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "180.00",
        "catmat_code": "0000152",
    },
    {
        "nome": "Cortador de grama",
        "descricao": "Cortador de grama a gasolina",
        "patrimonio": "PMF-2024-00153",
        "categoria_id": "5",
        "secretaria_id": "8",
        "quantidade": "6",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "1350.00",
        "catmat_code": "0000153",
    },
    {
        "nome": "Gerador de energia portátil",
        "descricao": "Gerador a gasolina 5000W",
        "patrimonio": "PMF-2024-00154",
        "categoria_id": "5",
        "secretaria_id": "8",
        "quantidade": "3",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "2800.00",
        "catmat_code": "0000154",
    },
    {
        "nome": "Computador desktop",
        "descricao": "Computador completo para setor agrícola",
        "patrimonio": "PMF-2024-00155",
        "categoria_id": "3",
        "secretaria_id": "8",
        "quantidade": "5",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "2200.00",
        "catmat_code": "0000155",
    },
    {
        "nome": "Mangueira de jardim 50m",
        "descricao": "Mangueira flexível para irrigação",
        "patrimonio": "PMF-2024-00156",
        "categoria_id": "5",
        "secretaria_id": "8",
        "quantidade": "15",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "120.00",
        "catmat_code": "0000156",
    },
    {
        "nome": "Regador de jardim",
        "descricao": "Regador plástico 10 litros",
        "patrimonio": "PMF-2024-00157",
        "categoria_id": "5",
        "secretaria_id": "8",
        "quantidade": "20",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "22.00",
        "catmat_code": "0000157",
    },
    {
        "nome": "Motosserra",
        "descricao": "Motosserra a gasolina",
        "patrimonio": "PMF-2024-00158",
        "categoria_id": "5",
        "secretaria_id": "8",
        "quantidade": "5",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "1200.00",
        "catmat_code": "0000158",
    },
    {
        "nome": "Roçadeira lateral",
        "descricao": "Roçadeira costal a gasolina",
        "patrimonio": "PMF-2024-00159",
        "categoria_id": "5",
        "secretaria_id": "8",
        "quantidade": "10",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "950.00",
        "catmat_code": "0000159",
    },
    {
        "nome": "Extintor de incêndio",
        "descricao": "Extintor pó químico ABC 6kg",
        "patrimonio": "PMF-2024-00160",
        "categoria_id": "5",
        "secretaria_id": "8",
        "quantidade": "8",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "180.00",
        "catmat_code": "0000160",
    },
    {
        "nome": "Mesa de atendimento social",
        "descricao": "Mesa para atendimento individualizado",
        "patrimonio": "PMF-2024-00161",
        "categoria_id": "1",
        "secretaria_id": "9",
        "quantidade": "20",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "430.00",
        "catmat_code": "0000161",
    },
    {
        "nome": "Cadeira estofada de espera",
        "descricao": "Cadeira estofada para sala de espera",
        "patrimonio": "PMF-2024-00162",
        "categoria_id": "1",
        "secretaria_id": "9",
        "quantidade": "40",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "210.00",
        "catmat_code": "0000162",
    },
    {
        "nome": "Armário de aço para prontuários",
        "descricao": "Armário com chave para documentos",
        "patrimonio": "PMF-2024-00163",
        "categoria_id": "1",
        "secretaria_id": "9",
        "quantidade": "15",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "780.00",
        "catmat_code": "0000163",
    },
    {
        "nome": "Computador desktop",
        "descricao": "Computador completo para CRAS/CREAS",
        "patrimonio": "PMF-2024-00164",
        "categoria_id": "3",
        "secretaria_id": "9",
        "quantidade": "25",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "2200.00",
        "catmat_code": "0000164",
    },
    {
        "nome": "Impressora multifuncional",
        "descricao": "Impressora laser multifuncional",
        "patrimonio": "PMF-2024-00165",
        "categoria_id": "3",
        "secretaria_id": "9",
        "quantidade": "8",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "890.00",
        "catmat_code": "0000165",
    },
    {
        "nome": "Colchão solteiro (kit acolhimento)",
        "descricao": "Colchão em espuma D28 solteiro",
        "patrimonio": "PMF-2024-00166",
        "categoria_id": "1",
        "secretaria_id": "9",
        "quantidade": "30",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "320.00",
        "catmat_code": "0000166",
    },
    {
        "nome": "Cobertor casal",
        "descricao": "Cobertor de fibra para distribuição",
        "patrimonio": "PMF-2024-00167",
        "categoria_id": "1",
        "secretaria_id": "9",
        "quantidade": "40",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "45.00",
        "catmat_code": "0000167",
    },
    {
        "nome": "Kit de higiene pessoal",
        "descricao": "Kit com itens básicos de higiene",
        "patrimonio": "PMF-2024-00168",
        "categoria_id": "4",
        "secretaria_id": "9",
        "quantidade": "100",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "28.00",
        "catmat_code": "0000168",
    },
    {
        "nome": "Fogão industrial 4 bocas",
        "descricao": "Fogão industrial para cozinha comunitária",
        "patrimonio": "PMF-2024-00169",
        "categoria_id": "1",
        "secretaria_id": "9",
        "quantidade": "5",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "950.00",
        "catmat_code": "0000169",
    },
    {
        "nome": "Geladeira duplex",
        "descricao": "Geladeira duplex frost free",
        "patrimonio": "PMF-2024-00170",
        "categoria_id": "1",
        "secretaria_id": "9",
        "quantidade": "6",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "2400.00",
        "catmat_code": "0000170",
    },
    {
        "nome": "Ventilador de coluna",
        "descricao": "Ventilador de coluna oscilante",
        "patrimonio": "PMF-2024-00171",
        "categoria_id": "1",
        "secretaria_id": "9",
        "quantidade": "20",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "165.00",
        "catmat_code": "0000171",
    },
    {
        "nome": "Telefone fixo",
        "descricao": "Aparelho de telefone fixo com fio",
        "patrimonio": "PMF-2024-00172",
        "categoria_id": "3",
        "secretaria_id": "9",
        "quantidade": "15",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "85.00",
        "catmat_code": "0000172",
    },
    {
        "nome": "Papel A4 (resma)",
        "descricao": "Resma de papel sulfite branco A4",
        "patrimonio": "PMF-2024-00173",
        "categoria_id": "2",
        "secretaria_id": "9",
        "quantidade": "60",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "24.90",
        "catmat_code": "0000173",
    },
    {
        "nome": "Pasta suspensa (caixa c/50)",
        "descricao": "Pasta suspensa kraft para arquivo",
        "patrimonio": "PMF-2024-00174",
        "categoria_id": "2",
        "secretaria_id": "9",
        "quantidade": "50",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "32.00",
        "catmat_code": "0000174",
    },
    {
        "nome": "Arquivo de aço 4 gavetas",
        "descricao": "Arquivo de aço para documentos",
        "patrimonio": "PMF-2024-00175",
        "categoria_id": "1",
        "secretaria_id": "9",
        "quantidade": "12",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "620.00",
        "catmat_code": "0000175",
    },
    {
        "nome": "Bebedouro elétrico",
        "descricao": "Bebedouro industrial de coluna",
        "patrimonio": "PMF-2024-00176",
        "categoria_id": "1",
        "secretaria_id": "9",
        "quantidade": "10",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "650.00",
        "catmat_code": "0000176",
    },
    {
        "nome": "Kit escolar para distribuição",
        "descricao": "Kit com material escolar básico",
        "patrimonio": "PMF-2024-00177",
        "categoria_id": "2",
        "secretaria_id": "9",
        "quantidade": "200",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "35.00",
        "catmat_code": "0000177",
    },
    {
        "nome": "Extintor de incêndio",
        "descricao": "Extintor pó químico ABC 6kg",
        "patrimonio": "PMF-2024-00178",
        "categoria_id": "5",
        "secretaria_id": "9",
        "quantidade": "8",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "180.00",
        "catmat_code": "0000178",
    },
    {
        "nome": "Detergente neutro (litro)",
        "descricao": "Detergente para limpeza geral",
        "patrimonio": "PMF-2024-00179",
        "categoria_id": "4",
        "secretaria_id": "9",
        "quantidade": "60",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "9.50",
        "catmat_code": "0000179",
    },
    {
        "nome": "Vassoura de nylon",
        "descricao": "Vassoura de cerdas de nylon",
        "patrimonio": "PMF-2024-00180",
        "categoria_id": "4",
        "secretaria_id": "9",
        "quantidade": "40",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "14.00",
        "catmat_code": "0000180",
    },
    {
        "nome": "Instrumento musical (kit fanfarra)",
        "descricao": "Kit de instrumentos para banda municipal",
        "patrimonio": "PMF-2024-00181",
        "categoria_id": "8",
        "secretaria_id": "10",
        "quantidade": "10",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "850.00",
        "catmat_code": "0000181",
    },
    {
        "nome": "Caixa de som amplificada",
        "descricao": "Caixa de som ativa para eventos",
        "patrimonio": "PMF-2024-00182",
        "categoria_id": "3",
        "secretaria_id": "10",
        "quantidade": "15",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "950.00",
        "catmat_code": "0000182",
    },
    {
        "nome": "Microfone sem fio",
        "descricao": "Microfone sem fio com receptor",
        "patrimonio": "PMF-2024-00183",
        "categoria_id": "3",
        "secretaria_id": "10",
        "quantidade": "20",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "320.00",
        "catmat_code": "0000183",
    },
    {
        "nome": "Mesa de som",
        "descricao": "Mesa de som digital para eventos",
        "patrimonio": "PMF-2024-00184",
        "categoria_id": "3",
        "secretaria_id": "10",
        "quantidade": "5",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "1800.00",
        "catmat_code": "0000184",
    },
    {
        "nome": "Refletor de palco",
        "descricao": "Refletor de LED para iluminação de palco",
        "patrimonio": "PMF-2024-00185",
        "categoria_id": "3",
        "secretaria_id": "10",
        "quantidade": "20",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "450.00",
        "catmat_code": "0000185",
    },
    {
        "nome": "Tenda para eventos",
        "descricao": "Tenda desmontável para eventos culturais",
        "patrimonio": "PMF-2024-00186",
        "categoria_id": "8",
        "secretaria_id": "10",
        "quantidade": "10",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "1200.00",
        "catmat_code": "0000186",
    },
    {
        "nome": "Cadeira plástica para eventos",
        "descricao": "Cadeira plástica empilhável",
        "patrimonio": "PMF-2024-00187",
        "categoria_id": "1",
        "secretaria_id": "10",
        "quantidade": "300",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "45.00",
        "catmat_code": "0000187",
    },
    {
        "nome": "Mesa dobrável para eventos",
        "descricao": "Mesa dobrável em polipropileno",
        "patrimonio": "PMF-2024-00188",
        "categoria_id": "1",
        "secretaria_id": "10",
        "quantidade": "50",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "180.00",
        "catmat_code": "0000188",
    },
    {
        "nome": "Palco modular (módulo)",
        "descricao": "Módulo de palco desmontável",
        "patrimonio": "PMF-2024-00189",
        "categoria_id": "8",
        "secretaria_id": "10",
        "quantidade": "8",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "1500.00",
        "catmat_code": "0000189",
    },
    {
        "nome": "Uniforme para grupo cultural (conjunto)",
        "descricao": "Conjunto de figurino para apresentações",
        "patrimonio": "PMF-2024-00190",
        "categoria_id": "7",
        "secretaria_id": "10",
        "quantidade": "40",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "150.00",
        "catmat_code": "0000190",
    },
    {
        "nome": "Material de artesanato (kit)",
        "descricao": "Kit de material para oficinas culturais",
        "patrimonio": "PMF-2024-00191",
        "categoria_id": "8",
        "secretaria_id": "10",
        "quantidade": "60",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "45.00",
        "catmat_code": "0000191",
    },
    {
        "nome": "Computador desktop",
        "descricao": "Computador completo para setor de cultura",
        "patrimonio": "PMF-2024-00192",
        "categoria_id": "3",
        "secretaria_id": "10",
        "quantidade": "8",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "2200.00",
        "catmat_code": "0000192",
    },
    {
        "nome": "Projetor multimídia",
        "descricao": "Projetor multimídia 3500 lumens",
        "patrimonio": "PMF-2024-00193",
        "categoria_id": "3",
        "secretaria_id": "10",
        "quantidade": "5",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "1850.00",
        "catmat_code": "0000193",
    },
    {
        "nome": "Impressora multifuncional",
        "descricao": "Impressora laser multifuncional",
        "patrimonio": "PMF-2024-00194",
        "categoria_id": "3",
        "secretaria_id": "10",
        "quantidade": "4",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "890.00",
        "catmat_code": "0000194",
    },
    {
        "nome": "Armário de aço",
        "descricao": "Armário de aço para escritório",
        "patrimonio": "PMF-2024-00195",
        "categoria_id": "1",
        "secretaria_id": "10",
        "quantidade": "6",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "620.00",
        "catmat_code": "0000195",
    },
    {
        "nome": "Extintor de incêndio",
        "descricao": "Extintor pó químico ABC 6kg",
        "patrimonio": "PMF-2024-00196",
        "categoria_id": "5",
        "secretaria_id": "10",
        "quantidade": "8",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "180.00",
        "catmat_code": "0000196",
    },
    {
        "nome": "Gerador de energia portátil",
        "descricao": "Gerador a gasolina 5000W",
        "patrimonio": "PMF-2024-00197",
        "categoria_id": "5",
        "secretaria_id": "10",
        "quantidade": "3",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "2800.00",
        "catmat_code": "0000197",
    },
    {
        "nome": "Papel A4 (resma)",
        "descricao": "Resma de papel sulfite branco A4",
        "patrimonio": "PMF-2024-00198",
        "categoria_id": "2",
        "secretaria_id": "10",
        "quantidade": "30",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "24.90",
        "catmat_code": "0000198",
    },
    {
        "nome": "Mesa de escritório",
        "descricao": "Mesa de escritório padrão",
        "patrimonio": "PMF-2024-00199",
        "categoria_id": "1",
        "secretaria_id": "10",
        "quantidade": "8",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "480.00",
        "catmat_code": "0000199",
    },
    {
        "nome": "Cadeira giratória",
        "descricao": "Cadeira giratória com apoio lombar",
        "patrimonio": "PMF-2024-00200",
        "categoria_id": "1",
        "secretaria_id": "10",
        "quantidade": "10",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "350.00",
        "catmat_code": "0000200",
    },
    {
        "nome": "Bola de futebol",
        "descricao": "Bola oficial de futebol de campo",
        "patrimonio": "PMF-2024-00201",
        "categoria_id": "8",
        "secretaria_id": "11",
        "quantidade": "60",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "85.00",
        "catmat_code": "0000201",
    },
    {
        "nome": "Bola de vôlei",
        "descricao": "Bola oficial de vôlei",
        "patrimonio": "PMF-2024-00202",
        "categoria_id": "8",
        "secretaria_id": "11",
        "quantidade": "40",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "75.00",
        "catmat_code": "0000202",
    },
    {
        "nome": "Rede de vôlei",
        "descricao": "Rede oficial para quadra de vôlei",
        "patrimonio": "PMF-2024-00203",
        "categoria_id": "8",
        "secretaria_id": "11",
        "quantidade": "15",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "180.00",
        "catmat_code": "0000203",
    },
    {
        "nome": "Trave de gol portátil",
        "descricao": "Trave de gol desmontável",
        "patrimonio": "PMF-2024-00204",
        "categoria_id": "8",
        "secretaria_id": "11",
        "quantidade": "8",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "950.00",
        "catmat_code": "0000204",
    },
    {
        "nome": "Colchonete para ginástica",
        "descricao": "Colchonete em espuma revestido",
        "patrimonio": "PMF-2024-00205",
        "categoria_id": "8",
        "secretaria_id": "11",
        "quantidade": "60",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "65.00",
        "catmat_code": "0000205",
    },
    {
        "nome": "Uniforme esportivo (conjunto)",
        "descricao": "Conjunto de uniforme para equipes municipais",
        "patrimonio": "PMF-2024-00206",
        "categoria_id": "7",
        "secretaria_id": "11",
        "quantidade": "100",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "95.00",
        "catmat_code": "0000206",
    },
    {
        "nome": "Apito esportivo",
        "descricao": "Apito profissional para arbitragem",
        "patrimonio": "PMF-2024-00207",
        "categoria_id": "8",
        "secretaria_id": "11",
        "quantidade": "30",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "12.00",
        "catmat_code": "0000207",
    },
    {
        "nome": "Cronômetro digital",
        "descricao": "Cronômetro digital de mão",
        "patrimonio": "PMF-2024-00208",
        "categoria_id": "8",
        "secretaria_id": "11",
        "quantidade": "15",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "45.00",
        "catmat_code": "0000208",
    },
    {
        "nome": "Equipamento de academia ao ar livre (módulo)",
        "descricao": "Módulo de aparelho para academia ao ar livre",
        "patrimonio": "PMF-2024-00209",
        "categoria_id": "8",
        "secretaria_id": "11",
        "quantidade": "10",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "1800.00",
        "catmat_code": "0000209",
    },
    {
        "nome": "Kit de tênis de mesa",
        "descricao": "Kit com mesa, redes e raquetes",
        "patrimonio": "PMF-2024-00210",
        "categoria_id": "8",
        "secretaria_id": "11",
        "quantidade": "12",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "320.00",
        "catmat_code": "0000210",
    },
    {
        "nome": "Bola de basquete",
        "descricao": "Bola oficial de basquete",
        "patrimonio": "PMF-2024-00211",
        "categoria_id": "8",
        "secretaria_id": "11",
        "quantidade": "30",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "90.00",
        "catmat_code": "0000211",
    },
    {
        "nome": "Tabela de basquete portátil",
        "descricao": "Tabela de basquete com suporte móvel",
        "patrimonio": "PMF-2024-00212",
        "categoria_id": "8",
        "secretaria_id": "11",
        "quantidade": "6",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "1500.00",
        "catmat_code": "0000212",
    },
    {
        "nome": "Cadeira plástica para arquibancada",
        "descricao": "Cadeira plástica empilhável",
        "patrimonio": "PMF-2024-00213",
        "categoria_id": "1",
        "secretaria_id": "11",
        "quantidade": "100",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "45.00",
        "catmat_code": "0000213",
    },
    {
        "nome": "Bebedouro elétrico",
        "descricao": "Bebedouro industrial de coluna",
        "patrimonio": "PMF-2024-00214",
        "categoria_id": "1",
        "secretaria_id": "11",
        "quantidade": "6",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "650.00",
        "catmat_code": "0000214",
    },
    {
        "nome": "Extintor de incêndio",
        "descricao": "Extintor pó químico ABC 6kg",
        "patrimonio": "PMF-2024-00215",
        "categoria_id": "5",
        "secretaria_id": "11",
        "quantidade": "6",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "180.00",
        "catmat_code": "0000215",
    },
    {
        "nome": "Computador desktop",
        "descricao": "Computador completo para setor de esportes",
        "patrimonio": "PMF-2024-00216",
        "categoria_id": "3",
        "secretaria_id": "11",
        "quantidade": "5",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "2200.00",
        "catmat_code": "0000216",
    },
    {
        "nome": "Armário de aço para material esportivo",
        "descricao": "Armário de aço para guarda de material",
        "patrimonio": "PMF-2024-00217",
        "categoria_id": "1",
        "secretaria_id": "11",
        "quantidade": "8",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "620.00",
        "catmat_code": "0000217",
    },
    {
        "nome": "Cone de sinalização",
        "descricao": "Cone de sinalização para atividades esportivas",
        "patrimonio": "PMF-2024-00218",
        "categoria_id": "5",
        "secretaria_id": "11",
        "quantidade": "40",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "25.00",
        "catmat_code": "0000218",
    },
    {
        "nome": "Mesa de escritório",
        "descricao": "Mesa de escritório padrão",
        "patrimonio": "PMF-2024-00219",
        "categoria_id": "1",
        "secretaria_id": "11",
        "quantidade": "6",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "480.00",
        "catmat_code": "0000219",
    },
    {
        "nome": "Papel A4 (resma)",
        "descricao": "Resma de papel sulfite branco A4",
        "patrimonio": "PMF-2024-00220",
        "categoria_id": "2",
        "secretaria_id": "11",
        "quantidade": "20",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "24.90",
        "catmat_code": "0000220",
    },
    {
        "nome": "Computador desktop",
        "descricao": "Computador completo para setor de desenvolvimento econômico",
        "patrimonio": "PMF-2024-00221",
        "categoria_id": "3",
        "secretaria_id": "12",
        "quantidade": "15",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "2200.00",
        "catmat_code": "0000221",
    },
    {
        "nome": "Notebook",
        "descricao": "Notebook 8GB RAM para uso administrativo",
        "patrimonio": "PMF-2024-00222",
        "categoria_id": "3",
        "secretaria_id": "12",
        "quantidade": "10",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "3200.00",
        "catmat_code": "0000222",
    },
    {
        "nome": "Impressora multifuncional",
        "descricao": "Impressora laser multifuncional",
        "patrimonio": "PMF-2024-00223",
        "categoria_id": "3",
        "secretaria_id": "12",
        "quantidade": "6",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "890.00",
        "catmat_code": "0000223",
    },
    {
        "nome": "Projetor multimídia",
        "descricao": "Projetor multimídia 3500 lumens",
        "patrimonio": "PMF-2024-00224",
        "categoria_id": "3",
        "secretaria_id": "12",
        "quantidade": "5",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "1850.00",
        "catmat_code": "0000224",
    },
    {
        "nome": "Mesa de escritório em L",
        "descricao": "Mesa de escritório em MDF formato L",
        "patrimonio": "PMF-2024-00225",
        "categoria_id": "1",
        "secretaria_id": "12",
        "quantidade": "15",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "480.00",
        "catmat_code": "0000225",
    },
    {
        "nome": "Cadeira giratória ergonômica",
        "descricao": "Cadeira giratória com apoio lombar",
        "patrimonio": "PMF-2024-00226",
        "categoria_id": "1",
        "secretaria_id": "12",
        "quantidade": "20",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "350.00",
        "catmat_code": "0000226",
    },
    {
        "nome": "Armário de aço 2 portas",
        "descricao": "Armário de aço para escritório",
        "patrimonio": "PMF-2024-00227",
        "categoria_id": "1",
        "secretaria_id": "12",
        "quantidade": "10",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "620.00",
        "catmat_code": "0000227",
    },
    {
        "nome": "Banner para feiras (unidade)",
        "descricao": "Banner impresso para divulgação em feiras",
        "patrimonio": "PMF-2024-00228",
        "categoria_id": "8",
        "secretaria_id": "12",
        "quantidade": "20",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "85.00",
        "catmat_code": "0000228",
    },
    {
        "nome": "Tenda para feiras",
        "descricao": "Tenda desmontável para feiras de negócios",
        "patrimonio": "PMF-2024-00229",
        "categoria_id": "8",
        "secretaria_id": "12",
        "quantidade": "8",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "1200.00",
        "catmat_code": "0000229",
    },
    {
        "nome": "Estande modular (kit)",
        "descricao": "Kit de estande desmontável para eventos",
        "patrimonio": "PMF-2024-00230",
        "categoria_id": "8",
        "secretaria_id": "12",
        "quantidade": "4",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "2500.00",
        "catmat_code": "0000230",
    },
    {
        "nome": "Mesa dobrável para eventos",
        "descricao": "Mesa dobrável em polipropileno",
        "patrimonio": "PMF-2024-00231",
        "categoria_id": "1",
        "secretaria_id": "12",
        "quantidade": "20",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "180.00",
        "catmat_code": "0000231",
    },
    {
        "nome": "Cadeira plástica para eventos",
        "descricao": "Cadeira plástica empilhável",
        "patrimonio": "PMF-2024-00232",
        "categoria_id": "1",
        "secretaria_id": "12",
        "quantidade": "60",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "45.00",
        "catmat_code": "0000232",
    },
    {
        "nome": "Papel A4 (resma)",
        "descricao": "Resma de papel sulfite branco A4",
        "patrimonio": "PMF-2024-00233",
        "categoria_id": "2",
        "secretaria_id": "12",
        "quantidade": "60",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "24.90",
        "catmat_code": "0000233",
    },
    {
        "nome": "Caneta esferográfica (caixa c/50)",
        "descricao": "Caneta azul esferográfica",
        "patrimonio": "PMF-2024-00234",
        "categoria_id": "2",
        "secretaria_id": "12",
        "quantidade": "30",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "18.00",
        "catmat_code": "0000234",
    },
    {
        "nome": "Grampeador de mesa",
        "descricao": "Grampeador metálico de mesa",
        "patrimonio": "PMF-2024-00235",
        "categoria_id": "2",
        "secretaria_id": "12",
        "quantidade": "20",
        "estado_conservacao": "novo",
        "valor_unitario_estimado": "22.00",
        "catmat_code": "0000235",
    },
    {
        "nome": "Telefone fixo digital",
        "descricao": "Aparelho de telefone fixo digital",
        "patrimonio": "PMF-2024-00236",
        "categoria_id": "3",
        "secretaria_id": "12",
        "quantidade": "15",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "95.00",
        "catmat_code": "0000236",
    },
    {
        "nome": "Extintor de incêndio",
        "descricao": "Extintor pó químico ABC 6kg",
        "patrimonio": "PMF-2024-00237",
        "categoria_id": "5",
        "secretaria_id": "12",
        "quantidade": "6",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "180.00",
        "catmat_code": "0000237",
    },
    {
        "nome": "Bebedouro elétrico",
        "descricao": "Bebedouro industrial de coluna",
        "patrimonio": "PMF-2024-00238",
        "categoria_id": "1",
        "secretaria_id": "12",
        "quantidade": "6",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "650.00",
        "catmat_code": "0000238",
    },
    {
        "nome": "Arquivo de aço 4 gavetas",
        "descricao": "Arquivo de aço para documentos",
        "patrimonio": "PMF-2024-00239",
        "categoria_id": "1",
        "secretaria_id": "12",
        "quantidade": "8",
        "estado_conservacao": "regular",
        "valor_unitario_estimado": "620.00",
        "catmat_code": "0000239",
    },
    {
        "nome": "Nobreak 1200VA",
        "descricao": "Nobreak para proteção de equipamentos",
        "patrimonio": "PMF-2024-00240",
        "categoria_id": "3",
        "secretaria_id": "12",
        "quantidade": "10",
        "estado_conservacao": "bom",
        "valor_unitario_estimado": "480.00",
        "catmat_code": "0000240",
    },
]


def run() -> None:
    create_db_and_tables()  # garante que a tabela existe, mesmo rodando isso sozinho

    with Session(engine) as session:
        for sec in SECRETARIAS_SEED:
            secretaria = Secretaria(**sec)
            session.add(secretaria)
            session.commit()
            session.refresh(secretaria)
            print(f"\n[ok] criado {secretaria.nome} (id={secretaria.id} | siga={secretaria.sigla})\n")
        
        for dados in USUARIOS_SEED:
            usuario = Usuario(**dados)
            session.add(usuario)
            session.commit()
            session.refresh(usuario)  # relê do banco pra pegar o id gerado
            print(f"\n[ok] criado {usuario.email} (id={usuario.id})\n")
        
        for cat in CATEGORIAS_SEED:
            categoria = Categoria(**cat)
            session.add(categoria)
            session.commit()
            session.refresh(categoria)
            print(f"\n[ok] criado {categoria.nome} (id={categoria.id})\n")
        
        for i in ITENS_SEED:
            item = Item(**i)
            session.add(item)
            session.commit()
            session.refresh(item)
            print(f"\n[ok] criado {item.nome} (id={item.id})\n")


if __name__ == "__main__":
    run()
